// To parse this JSON data, do
//
//     final gradeResponse = gradeResponseFromJson(jsonString);
//
// The code below is generated by https://app.quicktype.io/?l=dart
//
// Run `dart run build_runner build` in the root directory of this project to regenerate .g.dart file.

import 'package:json_annotation/json_annotation.dart';
import 'dart:convert';

part 'grade_response.g.dart';

GradeResponse gradeResponseFromJson(String str) => GradeResponse.fromJson(json.decode(str));

String gradeResponseToJson(GradeResponse data) => json.encode(data.toJson());

@JsonSerializable()
class GradeResponse {
  @JsonKey(name: "msg")
  String msg;
  @JsonKey(name: "ret")
  int ret;
  @JsonKey(name: "page")
  int page;
  @JsonKey(name: "rows")
  int rows;
  @JsonKey(name: "total")
  int total;
  @JsonKey(name: "totalPages")
  int totalPages;
  @JsonKey(name: "results")
  List<Grade> results;

  GradeResponse({
    required this.msg,
    required this.ret,
    required this.page,
    required this.rows,
    required this.total,
    required this.totalPages,
    required this.results,
  });

  factory GradeResponse.fromJson(Map<String, dynamic> json) => _$GradeResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GradeResponseToJson(this);
}

@JsonSerializable()
class Grade {
  @JsonKey(name: "xnxq")
  String semesterYearAndNo;
  @JsonKey(name: "xf")
  String credit;
  @JsonKey(name: "kcmc")
  String courseName;
  @JsonKey(name: "kcxz")
  String courseProperty;
  @JsonKey(name: "cjfxms")
  String? detail;
  @JsonKey(name: "zhcj")
  String score;
  @JsonKey(name: "hdxf")
  double creditGain;
  @JsonKey(name: "jd")
  double gradePoint;
  @JsonKey(name: "kcid")
  String courseId;

  Grade({
    required this.semesterYearAndNo,
    required this.credit,
    required this.courseName,
    required this.courseProperty,
    this.detail,
    required this.score,
    required this.creditGain,
    required this.gradePoint,
    required this.courseId,
  });

  factory Grade.fromJson(Map<String, dynamic> json) => _$GradeFromJson(json);

  Map<String, dynamic> toJson() => _$GradeToJson(this);

  String getPureCourseName() {
    return courseName.replaceAll('[$courseId]', '');
  }
}
